
with open('results.txt', 'w') as result:
      result.write('CML Report for Causal Modeling\n')
      result.write('\n')
      result.write('Logistic Regression\n')
      result.write('Best Accuracy: 98.5%\n')
      result.write('\n')
      result.write('Random Forest Classification\n')
      result.write('Best Accuracy: 94.7%\n')
      result.write('\n')
      result.write('Support Vector Machine Classifier \n')
      result.write('Best Accuracy: 96.49%\n')
      result.write('\n')
      result.write('Deep Neural Network \n')
      result.write('Best Accuracy: 96.49%\n')
      result.write('\n')
      result.write('================Causal Models==============')
      result.write('\n')
      result.write('Bayesian Network Big\n')
      result.write('Best Accuracy: 87.7.%\n')
      result.write('\n')
      result.write('Bayesian Network Small\n')
      result.write('Best Accuracy: 89.5%\n')